Repository ladybug-tools/honeybee-energy, pull requests merged in 2019-09, with the labels that each got.

#21 feat(schedule): Add objects for schedules and schedule types
  MANIFEST.in
  honeybee_energy/lib/_loadschedules.py
  honeybee_energy/lib/idf/__init__.py
  honeybee_energy/lib/idf/constructions/user_library.idf
  honeybee_energy/lib/idf/schedules/default.idf
  honeybee_energy/lib/idf/schedules/user_library.idf
  honeybee_energy/lib/materials.py
  honeybee_energy/lib/scheduletypelimits.py
  honeybee_energy/material/gas.py
  honeybee_energy/material/glazing.py
  honeybee_energy/material/opaque.py
  honeybee_energy/material/shade.py
  honeybee_energy/schedule/__init__.py
  honeybee_energy/schedule/day.py
  honeybee_energy/schedule/rule.py
  honeybee_energy/schedule/ruleset.py
  honeybee_energy/schedule/typelimit.py
  tests/idf/OfficeOccupancySchedule.idf
  tests/schedule_day_test.py
  tests/schedule_rule_test.py
  tests/schedule_ruleset_test.py
  tests/schedule_typelimit_test.py
  tests/standards/OpenStudio_Standards_schedules.json
Labels: critical, new development

#23 fix(pip): set include_package_data to True
  setup.py
Labels: bug, critical

#24 feat(schedule): Add ScheduleFixedInterval
  honeybee_energy/properties/model.py
  honeybee_energy/properties/shade.py
  honeybee_energy/schedule/day.py
  honeybee_energy/schedule/fixedinterval.py
  honeybee_energy/schedule/rule.py
  honeybee_energy/schedule/ruleset.py
  honeybee_energy/schedule/typelimit.py
  tests/csv/Electrochromic_Control.csv
  tests/csv/Electrochromic_Control_0.csv
  tests/csv/Electrochromic_Control_180.csv
  tests/csv/Electrochromic_Control_270.csv
  tests/csv/Electrochromic_Control_90.csv
  tests/idf/ElectrochromicControlSchedules.idf
  tests/idf/OfficeOccupancySchedule_Compact.idf
  tests/schedule_fixedinterval_test.py
  tests/schedule_ruleset_test.py
Labels: critical, enhancement, new development

#25 feat(load): Add objects to specify people, lighting and equipment
  honeybee_energy/construction.py
  honeybee_energy/lib/_loadschedules.py
  honeybee_energy/lib/_loadtypelimits.py
  honeybee_energy/lib/idf/schedules/default.idf
  honeybee_energy/lib/schedules.py
  honeybee_energy/lib/scheduletypelimits.py
  honeybee_energy/load/__init__.py
  honeybee_energy/load/_base.py
  honeybee_energy/load/equipment.py
  honeybee_energy/load/lighting.py
  honeybee_energy/load/people.py
  honeybee_energy/programtype.py
  honeybee_energy/properties/shade.py
  honeybee_energy/schedule/fixedinterval.py
  honeybee_energy/schedule/ruleset.py
  tests/load_equipment_test.py
  tests/load_lighting_test.py
  tests/load_people_test.py
  tests/schedule_day_test.py
Labels: critical, new development

#27 feat(programtype): Add complete object for ProgramType
  MANIFEST.in
  honeybee_energy/construction.py
  honeybee_energy/constructionset.py
  honeybee_energy/idealair.py
  honeybee_energy/lib/__init__.py
  honeybee_energy/lib/_loadconstructions.py
  honeybee_energy/lib/_loadconstructionsets.py
  honeybee_energy/lib/_loadprogramtypes.py
  honeybee_energy/lib/_loadschedules.py
  honeybee_energy/lib/_loadtypelimits.py
  honeybee_energy/lib/constructionsets.py
  honeybee_energy/lib/idf/__init__.py
  honeybee_energy/lib/idf/schedules/default.idf
  honeybee_energy/lib/library/__init__.py
  honeybee_energy/lib/library/constructions/default.idf
  honeybee_energy/lib/library/constructions/user_library.idf
  honeybee_energy/lib/library/constructionsets/default.json
  honeybee_energy/lib/library/programtypes/default.json
  honeybee_energy/lib/library/schedules/default.idf
  honeybee_energy/lib/library/schedules/user_library.idf
  honeybee_energy/lib/programtypes.py
  honeybee_energy/lib/schedules.py
  honeybee_energy/lib/scheduletypelimits.py
  honeybee_energy/load/_base.py
  honeybee_energy/load/equipment.py
  honeybee_energy/load/infiltration.py
  honeybee_energy/load/lighting.py
  honeybee_energy/load/people.py
  honeybee_energy/load/setpoint.py
  honeybee_energy/load/ventilation.py
  honeybee_energy/programtype.py
  honeybee_energy/properties/aperture.py
  honeybee_energy/properties/door.py
  honeybee_energy/properties/face.py
  honeybee_energy/properties/model.py
  honeybee_energy/properties/room.py
  honeybee_energy/properties/shade.py
  honeybee_energy/schedule/rule.py
  honeybee_energy/schedule/ruleset.py
  tests/constructionset_test.py
  tests/idealair_test.py
  tests/load_lighting_test.py
  tests/load_setpoint_test.py
  tests/model_extend_test.py
  tests/programtype_test.py
  tests/room_extend_test.py
  tests/schedule_ruleset_test.py
  tests/shade_extend_test.py
  tests/standards/OpenStudio_Standards_schedule.json
  tests/standards/OpenStudio_Standards_schedules.json
Labels: critical, enhancement, new development

#28 feat(schedule): Add more tests for ScheduleFixedInterval
  .travis.yml
  tests/schedule_fixedinterval_test.py
Labels: enhancement

#30 feat(construction): Split up construction module into several
  honeybee_energy/construction.py
  honeybee_energy/construction/__init__.py
  honeybee_energy/construction/_base.py
  honeybee_energy/construction/opaque.py
  honeybee_energy/construction/shade.py
  honeybee_energy/construction/window.py
  honeybee_energy/constructionset.py
  honeybee_energy/lib/_loadconstructions.py
  honeybee_energy/lib/constructions.py
  honeybee_energy/properties/aperture.py
  honeybee_energy/properties/door.py
  honeybee_energy/properties/face.py
  honeybee_energy/properties/model.py
  honeybee_energy/properties/shade.py
  tests/aperture_extend_test.py
  tests/construction_test.py
  tests/constructionset_test.py
  tests/door_extend_test.py
  tests/face_extend_test.py
  tests/model_extend_test.py
  tests/room_extend_test.py
  tests/shade_extend_test.py
Labels: enhancement
