Repository ladybug-tools/honeybee-energy, pull requests merged in 2021-09, with the labels that each got.

#755 fix(model): Fix validation of reversed constructions
  honeybee_energy/properties/model.py
  honeybee_energy/run.py
Labels: bug

#756 fix(model): Pass autocalculated parameters to OSM, IDF, gbXML
  honeybee_energy/cli/translate.py
  honeybee_energy/construction/window.py
  honeybee_energy/properties/model.py
  honeybee_energy/run.py
  honeybee_energy/writer.py
Labels: enhancement

#752 Added user_data to honeybee-energy
  .gitignore
  honeybee_energy/construction/_base.py
  honeybee_energy/construction/air.py
  honeybee_energy/construction/dynamic.py
  honeybee_energy/construction/opaque.py
  honeybee_energy/construction/shade.py
  honeybee_energy/construction/window.py
  honeybee_energy/construction/windowshade.py
  honeybee_energy/constructionset.py
  honeybee_energy/hvac/_base.py
  honeybee_energy/hvac/_template.py
  honeybee_energy/hvac/allair/_base.py
  honeybee_energy/hvac/doas/_base.py
  honeybee_energy/hvac/idealair.py
  honeybee_energy/internalmass.py
  honeybee_energy/load/_base.py
  honeybee_energy/load/equipment.py
  honeybee_energy/load/hotwater.py
  honeybee_energy/load/infiltration.py
  honeybee_energy/load/lighting.py
  honeybee_energy/load/people.py
  honeybee_energy/load/setpoint.py
  honeybee_energy/load/ventilation.py
  honeybee_energy/material/_base.py
  honeybee_energy/material/gas.py
  honeybee_energy/material/glazing.py
  honeybee_energy/material/opaque.py
  honeybee_energy/material/shade.py
  honeybee_energy/programtype.py
  honeybee_energy/schedule/fixedinterval.py
  honeybee_energy/schedule/ruleset.py
  tests/aperture_extend_test.py
  tests/construction_test.py
  tests/constructionset_test.py
  tests/door_extend_test.py
  tests/fixtures/__init__.py
  tests/fixtures/userdata_fixtures.py
  tests/hvac_allair_test.py
  tests/hvac_doas_test.py
  tests/hvac_heatcool_test.py
  tests/hvac_idealair_test.py
  tests/internalmass_test.py
  tests/json/constructionset_complete.json
  tests/json/program_type_office.json
  tests/load_equipment_test.py
  tests/load_hot_water_test.py
  tests/load_infiltration_test.py
  tests/load_lighting_test.py
  tests/load_people_test.py
  tests/load_setpoint_test.py
  tests/load_ventilation_test.py
  tests/material_gas_test.py
  tests/material_glazing_test.py
  tests/material_opaque_test.py
  tests/material_shade_test.py
  tests/programtype_test.py
  tests/schedule_fixedinterval_test.py
  tests/schedule_ruleset_test.py
Labels: enhancement

#757 fix(window): Improve the solar transmittance calculation
  honeybee_energy/construction/_base.py
  honeybee_energy/construction/window.py
  honeybee_energy/construction/windowshade.py
  honeybee_energy/material/glazing.py
  honeybee_energy/properties/model.py
Labels: enhancement

#758 fix(material): Fix minor errors in material classes
  honeybee_energy/material/gas.py
  honeybee_energy/material/glazing.py
Labels: enhancement

#759 fix(construction): Enable solar radiation in opaque temperature profile
  .github/workflows/ci.yaml
  honeybee_energy/construction/_base.py
  honeybee_energy/construction/opaque.py
  honeybee_energy/construction/window.py
  honeybee_energy/material/opaque.py
  tests/aperture_extend_test.py
  tests/cli_translate_test.py
  tests/construction_test.py
  tests/fixtures/userdata_fixtures.py
Labels: enhancement

#761 feat(simulate): Add an option to run OpenStudio Results measure
  honeybee_energy/cli/__init__.py
  honeybee_energy/cli/setconfig.py
  honeybee_energy/cli/simulate.py
  honeybee_energy/config.json
  honeybee_energy/config.py
  honeybee_energy/measure.py
  honeybee_energy/run.py
Labels: new development

#762 fix(measure): Handle measures that have no arguments
  honeybee_energy/measure.py
Labels: bug

#764 fix(simulate): Add options for visualization variables in simulate
  honeybee_energy/cli/simulate.py
  honeybee_energy/internalmass.py
  honeybee_energy/run.py
Labels: enhancement

#766 fix(docker): Include lbt-measures in the docker image
  Dockerfile
  build_image.sh
  setup.py
Labels: enhancement

#767 fix(docker): Include lbt-measures in the docker image
  Dockerfile
  build_image.sh
Labels: bug

#770 fix(simulate): Ensure measures path is included in base_osw
  honeybee_energy/cli/simulate.py
Labels: bug

#771 fix(resource): Fix several bugs in user_data implementation
  honeybee_energy/constructionset.py
  honeybee_energy/schedule/fixedinterval.py
  honeybee_energy/schedule/ruleset.py
Labels: bug

#772 fix(model): Add property to pass holes to OSM/IDF
  honeybee_energy/properties/model.py
Labels: bug
