Repository ladybug-tools/honeybee-energy, pull requests merged in 2022-03, with the labels that each got.

#832 feat(properties) add .properties to SHWSystem
  honeybee_energy/properties/extension.py
  honeybee_energy/shw.py
Labels: enhancement

#840 fix(model): Implement better dynamic window grouping
  honeybee_energy/properties/model.py
  honeybee_energy/schedule/ruleset.py
  tests/schedule_ruleset_test.py
Labels: enhancement

#841 fix(room): Exclude floor area when making plenum or ground
  honeybee_energy/properties/room.py
Labels: enhancement

#844 fix(hvac): Change radiant HVAC to have radiant_face_type
  honeybee_energy/hvac/doas/radiant.py
  honeybee_energy/hvac/heatcool/radiant.py
  tests/hvac_doas_test.py
  tests/hvac_heatcool_test.py
Labels: enhancement

#845 fix(config): Search for standards folder in AppData
  honeybee_energy/config.json
  honeybee_energy/config.py
Labels: enhancement

#847 fix(construction: Add to_idf methods to WindowConstructionDynamic
  honeybee_energy/construction/_base.py
  honeybee_energy/construction/dynamic.py
  honeybee_energy/construction/opaque.py
  honeybee_energy/construction/window.py
  honeybee_energy/construction/windowshade.py
  honeybee_energy/writer.py
Labels: enhancement

#848 fix(room): Duplicate daylight sensor points when duplicating rooms
  honeybee_energy/properties/room.py
Labels: bug

#849 fix(model): Add check to ensure constructions key is not required
  honeybee_energy/properties/model.py
Labels: bug

#850 fix(hvac): Refactor radiant templates for better reliability
  dev-requirements.txt
  honeybee_energy/hvac/doas/radiant.py
  honeybee_energy/hvac/heatcool/radiant.py
  honeybee_energy/properties/model.py
  tests/hvac_doas_test.py
  tests/hvac_heatcool_test.py
Labels: enhancement

#851 fix(model): Add dump_properties_to_dict method to ModelEnergyProperties
  honeybee_energy/cli/lib.py
  honeybee_energy/hvac/doas/radiant.py
  honeybee_energy/hvac/heatcool/radiant.py
  honeybee_energy/lib/_loadconstructions.py
  honeybee_energy/lib/_loadprogramtypes.py
  honeybee_energy/properties/model.py
  tests/model_extend_test.py
Labels: bug, enhancement

#852 fix(config): Add check to be sure user standards are set up correctly
  honeybee_energy/config.py
Labels: enhancement
