Repository ladybug-tools/honeybee-energy, pull requests merged in 2022-02, with the labels that each got.

#824 fix(translate): Fix case of FixedInterval occupancy schedules
  honeybee_energy/cli/translate.py
Labels: bug

#799 Added greenroof material
  honeybee_energy/material/opaque.py
  tests/material_opaque_test.py
Labels: enhancement

#826 feat(material): Add roof vegetation material
  honeybee_energy/construction/opaque.py
  honeybee_energy/material/gas.py
  honeybee_energy/material/glazing.py
  honeybee_energy/material/opaque.py
  honeybee_energy/material/shade.py
  tests/material_opaque_test.py
Labels: new development

#827 docs(typelimit): Fix a few docstrings
  honeybee_energy/schedule/typelimit.py
Labels: documentation

#828 fix(material): Add several fixes for vegetation materials
  honeybee_energy/construction/opaque.py
  honeybee_energy/material/dictutil.py
  honeybee_energy/material/opaque.py
  honeybee_energy/properties/room.py
Labels: bug, enhancement

#829 style(run): Enable files with non-ascii characters to be written
  honeybee_energy/run.py
Labels: enhancement

#830 fix(ruleset): Add better default for design days
  honeybee_energy/cli/translate.py
  honeybee_energy/schedule/ruleset.py
  honeybee_energy/schedule/typelimit.py
Labels: enhancement

#831 fix(opaque): Fix bug in the creation of soil_layer material
  honeybee_energy/material/opaque.py
Labels: bug

#833 fix(runperiod): Improve to_idf to align with OpenStudio
  honeybee_energy/simulation/parameter.py
  honeybee_energy/simulation/runperiod.py
Labels: enhancement

#834 fix(writer): Treat no setpoint the same as unconditioned
  honeybee_energy/properties/room.py
  honeybee_energy/writer.py
Labels: enhancement

#835 fix(edit): Add a command to assign annual-daylight control schedules
  honeybee_energy/cli/edit.py
  honeybee_energy/schedule/fixedinterval.py
Labels: enhancement

#836 fix(model): Add a method to patch missing adjacencies as adiabatic
  honeybee_energy/properties/model.py
  honeybee_energy/writer.py
Labels: enhancement
